### ISSUE TITLE
Adding additional clauses to query does not return predicted results

### ISSUE THREAD

**Issue by gemini-google-group** [wvanbergen/vertica#30] opened 2015-11-14 00:02 UTC
When running a query: 
```
connection.query("SELECT * my_table", row_style: :hash) { |row| puts row }
```
it will return all the rows of that table, understandably so.

However, when I try to add additional clauses, like "where" or "limit" statements, it does not return the values in a hash way, like the query above, instead:

```
connection.query("SELECT * my_table where id=1 limit 10", row_style: :hash) { |row| puts row }
```
returns something like this instead:
```
 #<Vertica::Result:0x000000082b0090
 @columns=
  [#<Vertica::Column:0x00000008286920
    @attribute_number=1,
    @converter=#<Proc:0x000000095ede50@/home/<my_computer>/.rvm/gems/ruby-2.2.0@work/gems/vertica-0.11.4/lib/vertica/column.rb:31 (lambda)>,
    @data_type=:integer,
    @format=:text,
    @name=:id,
    @size=8,
    @table_oid=95648006,
    @type_modifier=4294967295>,
   #<Vertica::Column:0x000000082868a8
    @attribute_number=2,
    @converter=#<Proc:0x000000095ede50@/home/<my_computer>/.rvm/gems/ruby-2.2.0@work/gems/vertica-0.11.4/lib/vertica/column.rb:31 (lambda)>,
    @data_type=:integer,
    @format=:text,
    @name=:something,
    @size=8,
    @table_oid=95648006,
    @type_modifier=4294967295>,
   #<Vertica::Column:0x00000008286858
    @attribute_number=3,
    @converter=#<Proc:0x000000095edc20@/home/<my_computer>/.rvm/gems/ruby-2.2.0@work/gems/vertica-0.11.4/lib/vertica/column.rb:37 (lambda)>,
    @data_type=:timestamp,
    @format=:text,
    @name=:start_time,
    @size=8,
    @table_oid=95648006,
    @type_modifier=4294967295>,
   #<Vertica::Column:0x00000008286830
    @attribute_number=4,
    @converter=#<Proc:0x000000095edc20@/home/<my_computer>/.rvm/gems/ruby-2.2.0@work/gems/vertica-0.11.4/lib/vertica/column.rb:37 (lambda)>,
    @data_type=:timestamp,
    @format=:text,
    @name=:end_time,
    @size=8,
    @table_oid=95648006,
    @type_modifier=4294967295>,
```

I was instead expecting, something more alone the lines of hashed values.
{id: 1, ....}
{id: 1, ....}

**Comment by wvanbergen** [comment] 2015-11-17 11:54
This is very odd. There is nothing in the code that looks at the SQL query you are trying to execute, so on the client end this cannot really happen unless the server is returning something unexpected.

- We only ever call your block from here: https://github.com/wvanbergen/vertica/blob/master/lib/vertica/query.rb#L79
- The value yielded to the block can **only** be a hash (or array if that's your row_style: https://github.com/wvanbergen/vertica/blob/master/lib/vertica/result.rb#L17-L24

What you are seeing is the `Vertica::Result` object, which should be returned by the `query` call, but should never be yielded into the block.

Is this consistently the case? Can you share a minimal example program that exposes this problem?

**Comment by gemini-google-group** [comment] 2015-11-20 22:01
So basically I am creating a view that joins rails admin and vertica. I am looking at vertica history on a table. The user selects the table columns they want, and I pass in the id of that record they want the history on. The idea would be make a query like so:

```ruby
def do_vertica_history
    @history = []
columns = "id, created_at, updated_at"
    connection = Vertica.connect(Rails.configuration.vertica_configurations[0])
    connection.query("SELECT #{columns} from #{Rails.configuration.vertica_configurations[1][:schema]}.table_name where id = #{self.id}") do |row|
      @history << row
    end
    connection.close
  end
```

when I run this, the `where id=<some id>` seems to return that mumbo jumbo above. I was hoping for something clean.

**Comment by wvanbergen** [comment] 2015-11-23 13:38
Really weird.

Does it work as expected when using buffered queries, i.e. by assigning the query result to a variable, and iterating over it afterwards?

``` ruby
result = connection.query("SELECT #{columns} from #{Rails.configuration.vertica_configurations[1][:schema]}.table_name where id = #{self.id}")
result.each do |row|
  ...
end
```

**Comment by gemini-google-group** [comment] 2015-12-04 21:46
Yes, that did seem to work. Thanks for your help! :)

**Comment by wvanbergen** [comment] 2016-06-24 10:54
Going to close this because you have worked around the problem, and I can't reproduce this. I added some tests to verify that streaming results are working as expected (see #45).

**Closed by wvanbergen** 2016-06-24 10:54 UTC
